export default {
  ER_USERNAME_REQUIRED: 'Username is required',
  ER_USERNAME_NOT_A_STRING: 'Username must be a string',
  ER_USERNAME_LENGTH: 'Username must be longer than 2 characters',
  ER_CLASSE_REQUIRED: 'Classe is required',
  ER_CLASSE_NOT_A_STRING: 'Classe must be a string',
  ER_CLASSE_LENGTH: 'Classe must be longer than 2 characters',
  ER_PASSWORD_REQUIRED: 'Password is required',
  ER_PASSWORD_NOT_A_STRING: 'Password must be a string',
  ER_PASSWORD_LENGTH: 'Password must be longer than 7 characters',
  ER_LEVEL_REQUIRED: 'Level is required',
  ER_LEVEL_NOT_A_NUMBER: 'Level must be a number',
  ER_LEVEL_CANNOT_BE_ZERO_OR_LESS: 'Level must be greater than 0',
  ER_USERNAME_AND_PASSWORD: 'Username or password invalid',
  ER_NAME_REQUIRED: 'Name is required',
  ER_NAME_NOT_A_STRING: 'Name must be a string',
  ER_NAME_LENGTH: 'Name must be longer than 2 characters',
  ER_AMOUNT_REQUIRED: 'Amount is required',
  ER_AMOUNT_NOT_A_STRING: 'Amount must be a string',
  ER_AMOUNT_LENGTH: 'Amount must be longer than 2 characters',
};